package com.fizzware.dramaticdoors.compat.registries;

import com.fizzware.dramaticdoors.compat.DDCompatAdvancement;
import com.fizzware.dramaticdoors.compat.DDCompatRecipe;
import com.fizzware.dramaticdoors.registry.DDNames;
import com.fizzware.dramaticdoors.registry.DDRegistry;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.properties.BlockSetType;

public class MoShizCompat
{
	public static void registerCompat() {
		registerBlocksItems();
		registerRecipes();
	}
	
	private static void registerBlocksItems() {
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_IRON_BAR, DDNames.SHORT_MS_IRON_BAR, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "iron_bar_door"), Blocks.IRON_DOOR), BlockSetType.IRON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BAMBOO, DDNames.SHORT_MS_BAMBOO, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "bamboo_door")), BlockSetType.BAMBOO, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_CHERRY, DDNames.SHORT_MS_CHERRY, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "cherry_door")), BlockSetType.CHERRY, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GLOWOOD, DDNames.SHORT_MS_GLOWOOD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "glowood_door")), BlockSetType.WARPED, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_HELLWOOD, DDNames.SHORT_MS_HELLWOOD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "hellwood_door")), BlockSetType.CRIMSON, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_MAPLE, DDNames.SHORT_MS_MAPLE, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "maple_door")), BlockSetType.OAK, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_SILVERBELL, DDNames.SHORT_MS_SILVERBELL, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "silverebell_door")), BlockSetType.BIRCH, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_TIGERWOOD, DDNames.SHORT_MS_TIGERWOOD, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "tigerwood_door")), BlockSetType.JUNGLE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_WILLOW, DDNames.SHORT_MS_WILLOW, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "willow_door")), BlockSetType.MANGROVE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GLASS, DDNames.SHORT_MS_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_SOUL_GLASS, DDNames.SHORT_MS_SOUL_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "soul_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_TINTED_GLASS, DDNames.SHORT_MS_TINTED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "tinted_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BLACK_GLASS, DDNames.SHORT_MS_BLACK_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "black_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GREY_GLASS, DDNames.SHORT_MS_GREY_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "grey_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIGHT_GREY_GLASS, DDNames.SHORT_MS_LIGHT_GREY_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "light_grey_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_WHITE_GLASS, DDNames.SHORT_MS_WHITE_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "white_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_RED_GLASS, DDNames.SHORT_MS_RED_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "red_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_ORANGE_GLASS, DDNames.SHORT_MS_ORANGE_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "orange_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_YELLOW_GLASS, DDNames.SHORT_MS_YELLOW_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "yellow_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIME_GLASS, DDNames.SHORT_MS_LIME_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "lime_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_GREEN_GLASS, DDNames.SHORT_MS_GREEN_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "green_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_CYAN_GLASS, DDNames.SHORT_MS_CYAN_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "cyan_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BLUE_GLASS, DDNames.SHORT_MS_BLUE_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "blue_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_PURPLE_GLASS, DDNames.SHORT_MS_PURPLE_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "purple_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_MAGENTA_GLASS, DDNames.SHORT_MS_MAGENTA_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "magenta_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_PINK_GLASS, DDNames.SHORT_MS_PINK_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "pink_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_LIGHT_BLUE_GLASS, DDNames.SHORT_MS_LIGHT_BLUE_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "light_blue_glass_door")), BlockSetType.STONE, true);
		DDRegistry.registerDoorBlockAndItem(DDNames.TALL_MS_BROWN_GLASS, DDNames.SHORT_MS_BROWN_GLASS, DDRegistry.getBlockFromResourceLocation(ResourceLocation.fromNamespaceAndPath("ms", "brown_glass_door")), BlockSetType.STONE, true);
	}
	
	private static void registerRecipes() {
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_IRON_BAR, ResourceLocation.fromNamespaceAndPath("ms", "iron_bar_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_BAMBOO, ResourceLocation.fromNamespaceAndPath("ms", "bamboo_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_CHERRY, ResourceLocation.fromNamespaceAndPath("ms", "cherry_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_GLOWOOD, ResourceLocation.fromNamespaceAndPath("ms", "glowood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_HELLWOOD, ResourceLocation.fromNamespaceAndPath("ms", "hellwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_MAPLE, ResourceLocation.fromNamespaceAndPath("ms", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_SILVERBELL, ResourceLocation.fromNamespaceAndPath("ms", "silverbell_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_TIGERWOOD, ResourceLocation.fromNamespaceAndPath("ms", "tigerwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_WILLOW, ResourceLocation.fromNamespaceAndPath("ms", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_SOUL_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "soul_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_BLACK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "black_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_LIGHT_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_WHITE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "white_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_RED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "red_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_ORANGE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "orange_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_YELLOW_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "yellow_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_LIME_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "lime_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_GREEN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "green_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_CYAN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "cyan_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_PURPLE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "purple_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_MAGENTA_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "magenta_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_PINK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "pink_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_LIGHT_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.SHORT_MS_BROWN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "brown_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_IRON_BAR, ResourceLocation.fromNamespaceAndPath("ms", "iron_bar_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_BAMBOO, ResourceLocation.fromNamespaceAndPath("ms", "bamboo_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_CHERRY, ResourceLocation.fromNamespaceAndPath("ms", "cherry_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_GLOWOOD, ResourceLocation.fromNamespaceAndPath("ms", "glowood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_HELLWOOD, ResourceLocation.fromNamespaceAndPath("ms", "hellwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_MAPLE, ResourceLocation.fromNamespaceAndPath("ms", "maple_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_SILVERBELL, ResourceLocation.fromNamespaceAndPath("ms", "silverbell_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_TIGERWOOD, ResourceLocation.fromNamespaceAndPath("ms", "tigerwood_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_WILLOW, ResourceLocation.fromNamespaceAndPath("ms", "willow_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_SOUL_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "soul_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "tinted_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_BLACK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "black_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_LIGHT_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_grey_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_WHITE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "white_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_RED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "red_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_ORANGE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "orange_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_YELLOW_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "yellow_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_LIME_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "lime_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_GREEN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "green_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_CYAN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "cyan_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_PURPLE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "purple_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_MAGENTA_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "magenta_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_PINK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "pink_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_LIGHT_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_blue_glass_door"));
		DDCompatAdvancement.createRecipeAdvancement(DDNames.TALL_MS_BROWN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "brown_glass_door"));
		
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_IRON_BAR, ResourceLocation.fromNamespaceAndPath("ms", "iron_bar_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_BAMBOO, ResourceLocation.fromNamespaceAndPath("ms", "bamboo_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_CHERRY, ResourceLocation.fromNamespaceAndPath("ms", "cherry_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_GLOWOOD, ResourceLocation.fromNamespaceAndPath("ms", "glowood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_HELLWOOD, ResourceLocation.fromNamespaceAndPath("ms", "hellwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_MAPLE, ResourceLocation.fromNamespaceAndPath("ms", "maple_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_SILVERBELL, ResourceLocation.fromNamespaceAndPath("ms", "silverbell_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_TIGERWOOD, ResourceLocation.fromNamespaceAndPath("ms", "tigerwood_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_WILLOW, ResourceLocation.fromNamespaceAndPath("ms", "willow_door"), true);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_SOUL_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "soul_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "tinted_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_BLACK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "black_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "grey_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_LIGHT_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_grey_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_WHITE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "white_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_RED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "red_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_ORANGE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "orange_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_YELLOW_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "yellow_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_LIME_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "lime_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_GREEN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "green_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_CYAN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "cyan_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "blue_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_PURPLE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "purple_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_MAGENTA_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "magenta_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_PINK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "pink_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_LIGHT_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_blue_glass_door"), false);
		DDCompatRecipe.createShortDoorRecipe(DDNames.SHORT_MS_BROWN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "brown_glass_door"), false);
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_IRON_BAR, ResourceLocation.fromNamespaceAndPath("ms", "iron_bar_door"), "tall_metal_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_BAMBOO, ResourceLocation.fromNamespaceAndPath("ms", "bamboo_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_CHERRY, ResourceLocation.fromNamespaceAndPath("ms", "cherry_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_GLOWOOD, ResourceLocation.fromNamespaceAndPath("ms", "glowood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_HELLWOOD, ResourceLocation.fromNamespaceAndPath("ms", "hellwood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_MAPLE, ResourceLocation.fromNamespaceAndPath("ms", "maple_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_SILVERBELL, ResourceLocation.fromNamespaceAndPath("ms", "silverbell_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_TIGERWOOD, ResourceLocation.fromNamespaceAndPath("ms", "tigerwood_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_WILLOW, ResourceLocation.fromNamespaceAndPath("ms", "willow_door"), "tall_wooden_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_SOUL_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "soul_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_TINTED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "tinted_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_BLACK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "black_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "grey_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_LIGHT_GREY_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_grey_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_WHITE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "white_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_RED_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "red_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_ORANGE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "orange_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_YELLOW_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "yellow_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_LIME_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "lime_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_GREEN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "green_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_CYAN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "cyan_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "blue_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_PURPLE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "purple_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_MAGENTA_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "magenta_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_PINK_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "pink_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_LIGHT_BLUE_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "light_blue_glass_door"), "tall_glass_door");
		DDCompatRecipe.createTallDoorRecipe(DDNames.TALL_MS_BROWN_GLASS, ResourceLocation.fromNamespaceAndPath("ms", "brown_glass_door"), "tall_glass_door");
	}
}
