# The Mod TOML file for Dramatic Doors.

modLoader="javafml"
loaderVersion="[47,)"

# License Schmicense
license="MIT"

[[mods]]
    modId="dramaticdoors"
    version="${version}"
    displayName="Dramatic Doors"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dramatic-doors"
    logoFile="icon.png"
    issueTrackerURL="https://github.com/Kitteh6660/DramaticDoors/issues"
    authors="FizzWare"
    credits="Thanks to the creators of Minecraft and Forge.\\n    Kitteh6660 for maintaining and updating this mod.\\n    WenXin2 for the updated Pokecube compat."
    description='''
    Doors that are barely tall enough to fit your player ... ?
    Doors that suffocate you when you ride ol' Blackjack the horse through? Enderman discrimination? Seriously?
    ... PAH!!

    Can we not have intrigue?  Whatever happened to the tender grace and elegance of a nice tall door? Where is the drama?!?
    Here. I have it. And now you can too.

    Gone are the ways of the past - with the new Dramatic Doors mod!

    With the modern era of innovations comes a new door type: the tall door and the short door.
    These 3-block-high doors come in every vanilla variety;
    Iron, Oak, Spruce, Birch, Acacia, Dark Oak, Jungle, Crimson, Warped, Mangrove! And in 1.20, the all-new Bamboo and Cherry!
    Craft one by putting 3 of the vanilla variant vertically in a crafting table.
    
    Short doors can be crafted by using the regular doors in stonecutter or with Woodworks installed: the sawmill for wooden doors.
    
    Now supports over 80 mods across Forge and Fabric!
    '''

[[dependencies.dramaticdoors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="forge"
    mandatory=false
    versionRange="[47.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="neoforge"
    mandatory=false
    versionRange="[21.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="morecraft"
    mandatory=false
    versionRange="[1.20,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="mcwdoors"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="tflostblocks"
    mandatory=false
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"